// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBucketList(arg1) {
  return window['go']['application']['handler']['GetBucketList'](arg1);
}

export function GetBucketOptions(arg1, arg2) {
  return window['go']['application']['handler']['GetBucketOptions'](arg1, arg2);
}

export function GetObjectImage(arg1, arg2, arg3) {
  return window['go']['application']['handler']['GetObjectImage'](arg1, arg2, arg3);
}

export function GetObjectList(arg1, arg2) {
  return window['go']['application']['handler']['GetObjectList'](arg1, arg2);
}

export function GetObjectThumbnail(arg1, arg2, arg3) {
  return window['go']['application']['handler']['GetObjectThumbnail'](arg1, arg2, arg3);
}

export function SetBucketOptions(arg1, arg2) {
  return window['go']['application']['handler']['SetBucketOptions'](arg1, arg2);
}
