// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {response} from '../models';
import {request} from '../models';

export function GetBucketList(arg1:context.Context):Promise<response.BucketList>;

export function GetBucketOptions(arg1:context.Context,arg2:string):Promise<response.BucketOption>;

export function GetObjectImage(arg1:context.Context,arg2:string,arg3:string):Promise<Array<number>>;

export function GetObjectList(arg1:context.Context,arg2:string):Promise<response.ObjectList>;

export function GetObjectThumbnail(arg1:context.Context,arg2:string,arg3:string):Promise<Array<number>>;

export function SetBucketOptions(arg1:context.Context,arg2:request.BucketOption):Promise<void>;
